### DISCUSSION TITLE
2013/07/15/understanding-sass-lists/

### DISCUSSION THREAD

**Discussion by giscus** [KittyGiraudel/site#168] [Announcements]
# 2013/07/15/understanding-sass-lists/

I’m Kitty Giraudel, a non-binary trans frontend developer based in Berlin, focused on accessibility and inclusivity.

https://kittygiraudel.com/2013/07/15/understanding-sass-lists/

**Comment by Omnikron13** [comment]
The cleanest (but most explicit/longest) version:

```scss
@use "sass:list";

$pages: ('home', 'about', 'products', 'contact');

$pages-class: ();
$pages-nav-class: ();

@each $i in $pages {
  $pages-class: list.append($pages-class, '.#{$i}');
  $pages-nav-class: list.append($pages-nav-class, '.nav-#{$i}');
}

$selector: list.zip($pages-class, $pages-nav-class);

#{$selector} {
  style: awesome;
} 
```
